# Generated by Django 5.1 on 2024-08-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionFinished',
            fields=[
                ('aiquestion', models.AutoField(primary_key=True, serialize=False)),
                ('keywords', models.JSONField(default=list)),
                ('content', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'AIQuestionFinished',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExQuestionOngoing',
            fields=[
                ('exquestion', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ExQuestionOngoing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list)),
                ('sentence', models.CharField(max_length=100)),
                ('sentence_image', models.CharField(blank=True, default='', max_length=256)),
                ('content', models.CharField(max_length=200)),
                ('written_at', models.DateField()),
                ('release_or_not', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ReadingNote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserReadingNote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('written_at', models.DateField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'db_table': 'PreReadingNote',
                'managed': True,
            },
        ),
    ]
