# Generated by Django 5.1 on 2024-08-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_initial'),
        ('readingNote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prereadingnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingnote',
            name='aiquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='readingNote.aiquestionfinished'),
        ),
        migrations.AddField(
            model_name='readingnote',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AddField(
            model_name='userreadingnote',
            name='aiquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='readingNote.aiquestionfinished'),
        ),
        migrations.AddField(
            model_name='userreadingnote',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AddField(
            model_name='userreadingnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
