# Generated by Django 5.1 on 2024-08-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingNote', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreadingnote',
            name='exquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='readingNote.exquestionongoing'),
        ),
    ]
