# Generated by Django 5.1 on 2024-08-25 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingNote', '0003_userreadingnote_exquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreadingnote',
            name='aiquestion',
        ),
        migrations.RemoveField(
            model_name='readingnote',
            name='aiquestion',
        ),
        migrations.RemoveField(
            model_name='userreadingnote',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userreadingnote',
            name='exquestion',
        ),
        migrations.RemoveField(
            model_name='userreadingnote',
            name='user',
        ),
        migrations.RenameField(
            model_name='exquestionongoing',
            old_name='exquestion',
            new_name='exquestion_id',
        ),
        migrations.AddField(
            model_name='readingnote',
            name='exquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='readingNote.exquestionongoing'),
        ),
        migrations.AddField(
            model_name='readingnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AIQuestionFinished',
        ),
        migrations.DeleteModel(
            name='UserReadingNote',
        ),
    ]
