# Generated by Django 5.1 on 2024-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingNote', '0004_remove_userreadingnote_aiquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingnote',
            old_name='release_or_not',
            new_name='disclosure',
        ),
        migrations.RemoveField(
            model_name='prereadingnote',
            name='title',
        ),
        migrations.RemoveField(
            model_name='readingnote',
            name='sentence',
        ),
        migrations.AddField(
            model_name='prereadingnote',
            name='disclosure',
            field=models.BooleanField(default=False),
        ),
    ]
