# Generated by Django 5.1 on 2024-08-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingNote', '0005_rename_release_or_not_readingnote_disclosure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingnote',
            name='sentence_image',
        ),
    ]
