# Generated by Django 5.1 on 2024-09-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingNote', '0006_remove_readingnote_sentence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingnote',
            name='content',
            field=models.TextField(),
        ),
    ]
