# Generated by Django 5.1 on 2024-08-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksentence',
            name='represent_sentence',
            field=models.JSONField(default=list),
        ),
    ]
