# Generated by Django 5.1 on 2024-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_delete_briefreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='reading_time',
        ),
        migrations.AddField(
            model_name='userbook',
            name='reading_percent',
            field=models.IntegerField(default=0),
        ),
    ]
