# Generated by Django 5.1 on 2024-08-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_userbook_reading_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='buying_at',
        ),
    ]
