# Generated by Django 5.1 on 2024-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookdetail_buying_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.CharField(default='', max_length=20),
        ),
    ]
