# Generated by Django 5.1 on 2024-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_isbn_book_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.CharField(max_length=20),
        ),
    ]
