# Generated by Django 5.1 on 2024-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_isbn_alter_book_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='table_of_content',
            field=models.CharField(default='', max_length=200),
        ),
    ]
