# Generated by Django 5.1 on 2024-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_table_of_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='table_of_content',
            field=models.CharField(max_length=200),
        ),
    ]
