# Generated by Django 5.1 on 2024-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_table_of_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.CharField(max_length=100),
        ),
    ]
