# Generated by Django 5.1 on 2024-08-25 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0003_delete_briefreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('bookreview_id', models.AutoField(primary_key=True, serialize=False)),
                ('keywords', models.JSONField(default=list)),
                ('brief_review', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('written_at', models.DateField()),
                ('release_or_not', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'db_table': 'BookReview',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserBookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('bookreview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookReview.bookreview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserBookReview',
                'managed': True,
            },
        ),
    ]
