# Generated by Django 5.1 on 2024-08-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('aiquestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'AIQuestion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='aiquestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookReview.aiquestion'),
        ),
        migrations.DeleteModel(
            name='UserBookReview',
        ),
    ]
