# Generated by Django 5.1 on 2024-08-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0002_aiquestion_bookreview_user_bookreview_aiquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='release_or_not',
            new_name='disclosure',
        ),
    ]
