# Generated by Django 5.1 on 2024-08-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0003_rename_release_or_not_bookreview_disclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestion',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='aiquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookReview.aiquestion'),
        ),
    ]
