# Generated by Django 5.1 on 2024-08-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0004_alter_aiquestion_content_alter_bookreview_aiquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquestion',
            name='content',
        ),
        migrations.AddField(
            model_name='aiquestion',
            name='aiquestion_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='aiquestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookReview.aiquestion'),
        ),
    ]
