# Generated by Django 5.1 on 2024-09-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0005_remove_aiquestion_content_aiquestion_aiquestion_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='content',
            field=models.TextField(),
        ),
    ]
