name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # 최신 코드 가져오기

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.6  # EC2에 SSH 접속
      with:
        host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
        username: ${{ secrets.REMOTE_USER }} # 사용자
        key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
        port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
        script: |
          cd server_version2/todokVer2  # 프로젝트 폴더로 이동
          git pull origin main  # 최신 코드 가져오기
          sudo systemctl restart uwsgi  # 서비스 재시작
